---
title: "Prices"
---

```{r setup}
#| include: false

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(googlesheets4)
library(tidyr)
library(kableExtra)
barchart_key <- Sys.getenv("BARCHART_Key")
json_key_path <- Sys.getenv("GOOGLE_SHEETS_JSON")
gs4_auth(path = json_key_path)
```

<https://forms.gle/PscmhTrE13roMsw37>

```{r}
DATA1 <- read.csv(url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", barchart_key ,"&symbol=ZC*1&type=dailyNearest&startDate=20190101"))) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(symbol, Date, close) %>%
  mutate(symbol = substr(symbol, 1,2)) 

DATA2 <- read.csv(url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", barchart_key ,"&symbol=ZS*1&type=dailyNearest&startDate=20190101"))) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(symbol, Date, close) %>%
  mutate(symbol = substr(symbol, 1,2))

DATA3 <- read.csv(url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", barchart_key ,"&symbol=ZW*1&type=dailyNearest&startDate=20190101"))) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(symbol, Date, close) %>%
  mutate(symbol = substr(symbol, 1,2))

DATA <- rbind(DATA1, DATA2, DATA3)


DATA %>% 
  ggplot(aes(x = Date, y = close, color = symbol)) + 
  theme_bw() +
  theme(plot.title = element_text(size = 20),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)) +
  labs(title = "Prices of Nearby Corn, Soybeans, & Wheat Futures",
       y = "Cents per bushel",
       x = "") + 
  
  geom_line(size = 1)
```

```{r}
c_percent_spread <- read.csv(
  url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", 
             barchart_key ,
             "&symbol=ZC*1&type=dailyNearest&startDate=20000101"))
  ) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(Date, close) %>% 
  inner_join(
    read.csv(url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", 
                        barchart_key,"&symbol=ZC*2&type=dailyNearest&startDate=20000101"))
             ) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(Date, close), by = 'Date') %>% 
  mutate(spread = close.x - close.y) %>% 
  mutate(percent_spread = (close.x - close.y)/close.x) %>% 
  select(Date, spread, percent_spread)
  
s_percent_spread <- read.csv(
  url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", 
             barchart_key ,
             "&symbol=ZS*1&type=dailyNearest&startDate=20000101"))
  ) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(Date, close) %>% 
  inner_join(
    read.csv(url(paste0("http://ondemand.websol.barchart.com/getHistory.csv?apikey=", 
                        barchart_key,"&symbol=ZS*2&type=dailyNearest&startDate=20000101"))
             ) %>%
  mutate(Date = as.Date(tradingDay)) %>% 
  select(Date, close), by = 'Date') %>%
  mutate(spread = close.x - close.y) %>% 
  mutate(percent_spread = (close.x - close.y)/close.x) %>% 
  select(Date, spread, percent_spread)

calendar_spreads <- inner_join(c_percent_spread, s_percent_spread, by = 'Date')

colnames(calendar_spreads) <- c("Date", "Corn_Cal_Spread", "Corn_Cal_Spread_Perc", "Soy_Cal_Spread", "Soy_Cal_Spread_Perc")

calendar_spreads %>% pivot_longer(cols = -Date, names_to = 'C_S', values_to = 'Spread') %>% 
  ggplot(aes(x = Date, y = Spread, color = C_S)) + geom_line()

calendar_spreads %>% write.csv(file = "calendar_spreads.csv")
```
